services:
  selling-points:
    image: selling-points
    container_name: selling-points-container
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/selling_points_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "5005:5005"
    networks:
      - main-network
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis/redis-stack:7.4.0-v3
    container_name: redis_v2
    ports:
      - "6379:6379"
    networks:
      - main-network
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:8.0.8
    container_name: mongodb_v2
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=selling_points_db
    networks:
      - main-network
    volumes:
      - mongodb_data:/data

networks:
  main-network:

volumes:
  redis_data:
  mongodb_data: